#!/usr/bin/env bash
# mDNS Reflector add-on: generate an Avahi config from the add-on options
# and run the daemon in the foreground.
set -euo pipefail

# Overridable so the logic can be exercised outside the container.
CONFIG_PATH="${CONFIG_PATH:-/data/options.json}"
AVAHI_CONF="${AVAHI_CONF:-/etc/avahi/avahi-daemon.conf}"

log() { echo "[$(date '+%H:%M:%S')] $*"; }
fail() { log "FATAL: $*"; exit 1; }

[[ -f "${CONFIG_PATH}" ]] || fail "No options.json; is this running as a Home Assistant add-on?"

# Plain while-read rather than mapfile, so this runs on bash 3.x too.
INTERFACES=()
while IFS= read -r line; do [[ -n "${line}" ]] && INTERFACES+=("${line}"); done \
    < <(jq -r '.interfaces[]?' "${CONFIG_PATH}")
FILTERS=()
while IFS= read -r line; do [[ -n "${line}" ]] && FILTERS+=("${line}"); done \
    < <(jq -r '.reflect_filters[]?' "${CONFIG_PATH}")
REFLECT_IPV6=$(jq -r '.reflect_ipv6 // false' "${CONFIG_PATH}")
REFLECT_BETWEEN=$(jq -r '.reflect_between_ipv4_ipv6 // false' "${CONFIG_PATH}")
DISALLOW_OTHER=$(jq -r '.disallow_other_stacks // false' "${CONFIG_PATH}")
ALLOW_P2P=$(jq -r '.allow_point_to_point // false' "${CONFIG_PATH}")
LOG_LEVEL=$(jq -r '.log_level // "info"' "${CONFIG_PATH}")

# ---- validate interfaces -------------------------------------------------
(( ${#INTERFACES[@]} >= 2 )) || fail \
  "Need at least 2 interfaces to reflect between; got ${#INTERFACES[@]}."

missing=()
for iface in "${INTERFACES[@]}"; do
    if ip -o link show "${iface}" &>/dev/null; then
        addr=$(ip -4 -o addr show "${iface}" 2>/dev/null | awk '{print $4}' | paste -sd, -)
        if [[ -n "${addr}" ]]; then
            log "interface ${iface}: present (${addr})"
        else
            log "interface ${iface}: present, but has NO IPv4 address"
            log "  WARNING: Avahi will ignore an interface with no address."
        fi
    else
        missing+=("${iface}")
        log "interface ${iface}: MISSING on host"
    fi
done

if (( ${#missing[@]} > 0 )); then
    log ""
    log "Interfaces not found: ${missing[*]}"
    log "Create VLAN sub-interfaces on the host first, e.g.:"
    log "  ha network vlan end0 20 --ipv4-method static --ipv4-address 192.168.20.5/24"
    log "(host_network must also be true, which this add-on sets.)"
    fail "Refusing to start with missing interfaces."
fi

# ---- build config --------------------------------------------------------
yesno() { [[ "$1" == "true" ]] && echo yes || echo no; }

filter_line=""
if (( ${#FILTERS[@]} > 0 )); then
    filter_line="reflect-filters=$(IFS=,; echo "${FILTERS[*]}")"
    log "reflecting only: ${FILTERS[*]}"
else
    log "reflect_filters empty: reflecting ALL service types between ${INTERFACES[*]}"
    log "  The host's own announcements are never reflected - Avahi drops packets"
    log "  originating from its own addresses - so Home Assistant and Scrypted"
    log "  services are excluded automatically."
    log "  Set reflect_filters to restrict which services may cross VLANs."
fi

cat > "${AVAHI_CONF}" <<EOF
# Generated by the mDNS Reflector add-on - edits here are overwritten.
[server]
use-ipv4=yes
use-ipv6=$(yesno "${REFLECT_IPV6}")
allow-interfaces=$(IFS=,; echo "${INTERFACES[*]}")
# No D-Bus in this container; the daemon is standalone.
enable-dbus=no
# 'no' lets Avahi share :5353 with Home Assistant's own python-zeroconf stack.
disallow-other-stacks=$(yesno "${DISALLOW_OTHER}")
allow-point-to-point=$(yesno "${ALLOW_P2P}")

[wide-area]
enable-wide-area=no

[publish]
# This add-on only relays other hosts' records. Publishing would announce the
# Pi's own hostname on every VLAN and collide with Home Assistant's records.
disable-publishing=yes
disable-user-service-publishing=yes
publish-addresses=no
publish-hinfo=no
publish-workstation=no

[reflector]
enable-reflector=yes
reflect-ipv=$(yesno "${REFLECT_BETWEEN}")
${filter_line}
EOF

log "--- avahi-daemon.conf ---"
sed 's/^/    /' "${AVAHI_CONF}"
log "-------------------------"

# ---- run -----------------------------------------------------------------
# --no-chroot:     the Debian package chroots by default, which fails in a container
# --no-drop-root:  avoids uid/permission problems on the add-on's writable paths
args=(--no-chroot --no-drop-root -f "${AVAHI_CONF}")
if [[ "${LOG_LEVEL}" == "debug" ]]; then
    args+=(--debug)
fi

log "starting avahi-daemon reflecting between: ${INTERFACES[*]}"
exec avahi-daemon "${args[@]}"
